# Site settings

title: "Bulma: a modern CSS framework"
description: > # this means to ignore newlines until "baseurl:"
  Bulma is a CSS framework based on Flexbox and built with Sass
baseurl: ""
url: "http://bulma.io"
github: "https://github.com/jgthms/bulma"
download: "https://github.com/jgthms/bulma/archive/0.0.4.zip"
version: 0.0.4
permalink: pretty
sass:
  sass_dir: node_modules

# Build settings

highlighter: pygments
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: pygments
